name: autoSyncSingleCommit
on:
  push:
    branches:
      - main
jobs:
  autoSyncNotRequired:
    if: contains(github.event.commits[github.event.commits.length - 1].message.toLowerCase(), 'merge pull request #')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
      - name: Ignore this single commit
        run: |
          echo Commit has came from merged pull request! Please ignore it!
  autoSyncSingleCommit:
    if: "!contains(github.event.commits[github.event.commits.length - 1].message.toLowerCase(), 'merge pull request #')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout the repository
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo Autosync a single commit that is not comming from a merged pull request
          echo ${{ github.event.pull_request }}
          echo "$GITHUB_CONTEXT"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.AUTOSYNC_TOKEN_CLOUD_HOSTED_REPO }}
          repository: ${{ secrets.AUTOSYNC_CLOUD_HOSTED_REPO_URL }}
          event-type: ${{ secrets.AUTOSYNC_EVENT_TYPE }}
          client-payload: '{"ref": "${{ github.ref }}", "prNumber": "${{ github.event.pull_request.number }}", "sha": "${{ github.sha }}"}'
